apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-environments
spec:
  generators:
  - git:
      repoURL: ephemeralenv
      revision: main
      directories:
      - path: "deployments/*"
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}-cluster'
    spec:
      project: default
      source:
        repoURL: git@github.com:edudip/ephemeralenv.git
        targetRevision: main
        path: "vcluster"
        helm:
          valueFiles:
          - "../{{ path.basename }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: {{path.basename}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          # security measurement
          allowEmpty: false