apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-environments
spec:
  generators:
  - git:
      repoURL: git@github.com:edudip/ephemeralenv.git
      revision: main
      directories:
      - path: "deployments/*"
  template:
    metadata:
      name: 'cluster-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:edudip/ephemeralenv.git
        targetRevision: main
        path: "vcluster"
        helm:
          valueFiles:
          - "../deployments/{{ path.basename }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
          # security measurement
          allowEmpty: false