apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-environments
spec:
  generators:
  - git:
      repoURL: git@github.com:edudip/ephemeral.git
      revision: main
      directories:
      - path: "environments/deployments/*"
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}-cluster'
    spec:
      project: default
      source:
        repoURL: git@github.com:edudip/ephemeralenv.git
        targetRevision: main
        path: "environments/chart"
        helm:
          valueFiles:
          - "../{{ path.basename }}/values.yaml"
      destination:
        name: 'in-cluster'
        namespace: argo
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          # security measurement
          allowEmpty: false