apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nextapps-staging
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:edudip/ephemeralenv.git
              revision: main
              directories:
              - path: "deployments/*"
          - list:
              elements:
              - app: next
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
        # longhorn etc.
            - key: staging-components
              operator: In
              values:
                - base-cluster
        - matchExpressions:
        # database, cache etc.
            - key: staging-components
              operator: In
              values:
                - service-dependencies
        # our applications
        - matchExpressions:
            - key: staging-components
              operator: In
              values:
                - next
  template:
    metadata:
      name: 'vcluster-{{path.basename}}-apps'
      labels:
        staging-components: '{{app}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:edudip/ephemeralenv.git
        targetRevision: main
        path: "deployments/{{path.basename}}/apps/{{app}}/"
        plugin:
      destination:
        server: 'https://cluster-{{ path.basename }}.vcluster-{{ path.basename }}'
        namespace: 'next-apps-{{ path.basename }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
          # security measurement
          allowEmpty: false