apiVersion: v2
name: vcluster
description: A Helm chart for vcluster deployment
type: application
version: 0.1.0
appVersion: "0.25.0"
dependencies:
  - name: vcluster
    version: 0.25.0
    repository: https://charts.loft.sh
