apiVersion: v2
name: staging-service-dependencies-helm-chart
description: A Helm chart to deploy our staging-environment service-dependencies
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mailpit
    version: "0.25.0"
    repository: https://jouve.github.io/charts/
  - name: nats
    version: "1.3.7"
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: pxc-operator
    version: 1.16.1
    repository: https://percona.github.io/percona-helm-charts/
    condition: pxc-operator.enabled